services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: porishrom
      POSTGRES_PASSWORD: porishrom
      POSTGRES_DB: porishrom
    ports:
      - "5433:5432"
    volumes:
      - porishrom_postgres_data:/var/lib/postgresql/data

volumes:
  porishrom_postgres_data:
