import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowRight, BriefcaseBusiness, ClipboardList, MessageSquare, Search, Settings, Users, WalletCards } from "lucide-react";

import { listConnectionsAction } from "@/app/connections/actions";
import { listConversationsAction } from "@/app/messages/actions";
import { getFinancialHistoryAction, listWorkAssignmentsAction } from "@/app/work-assignments/actions";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { getCurrentUser } from "@/lib/current-user";

const ACTIONS = [["Find freelancers", "Discover approved freelancers for your next project.", "/freelancers", Search], ["Messages", "Review requests and continue conversations.", "/dashboard/client/messages", MessageSquare], ["Payments", "Review verified payments and current work value.", "/dashboard/client/payments", WalletCards], ["Profile", "Keep company information current.", "/dashboard/client/settings", Settings]] as const;
const TERMINAL = new Set(["completed", "cancelled", "rejected"]);
const money = (value: number, currency = "INR") => new Intl.NumberFormat("en-IN", { style: "currency", currency, maximumFractionDigits: 0 }).format(value);
const initials = (name: string) => name.trim().split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase();

export default async function ClientDashboardPage() {
  const user = await getCurrentUser();
  if (!user) redirect("/auth/login");
  const [connectionResult, conversationResult, financial] = await Promise.all([listConnectionsAction().catch(() => null), listConversationsAction().catch(() => null), getFinancialHistoryAction().catch(() => null)]);
  const connections = connectionResult ?? [];
  const conversations = conversationResult ?? [];
  const work = (await Promise.all(conversations.map((conversation) => listWorkAssignmentsAction(conversation.id).catch(() => [])))).flat();
  const activeWork = work.filter(({ status }) => !TERMINAL.has(status));
  const activeConnections = connections.filter(({ status }) => status === "accepted");
  const incoming = connections.filter(({ status, receiverId }) => status === "pending" && receiverId === user.id);
  const currency = financial?.history[0]?.currency ?? "INR";

  return <main className="mx-auto flex w-full max-w-7xl min-w-0 flex-col gap-4 py-1 pb-24 md:py-1 md:pb-1 sm:gap-5">
    <div className="flex min-w-0 flex-col gap-4 md:hidden">
      <header className="border-b border-border pb-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-metadata font-semibold uppercase tracking-[.16em] text-primary">Client workspace</p><h1 className="mt-1 font-heading text-2xl font-semibold tracking-tight text-foreground">Welcome back, {user.name}</h1><p className="mt-1 max-w-sm text-metadata leading-5 text-muted-foreground">Your company, freelancer relationships, work, and payments at a glance.</p></div><Button render={<Link href="/dashboard/client/settings" />} nativeButton={false} variant="outline" size="sm" className="shrink-0 border-border bg-card text-foreground hover:bg-muted hover:text-foreground dark:bg-card dark:hover:bg-muted"><Settings data-icon="inline-start" /><span className="sr-only">Profile settings</span></Button></div><Link href="/dashboard/client/settings" className="mt-3 inline-flex items-center text-metadata font-semibold text-primary hover:text-foreground">Profile settings <ArrowRight className="ml-1 size-3.5" /></Link></header>
      <section className="grid grid-cols-2 gap-px overflow-hidden rounded-xl border border-border bg-border">
        <MobileMetric icon={WalletCards} label="Verified payments" value={financial ? money(financial.summary.verifiedAmount, currency) : "Unavailable"} detail="verified total" accent />
        <MobileMetric icon={WalletCards} label="Pending payment" value={financial ? money(financial.summary.pendingAmount, currency) : "Unavailable"} detail="awaiting verification" />
        <MobileMetric icon={BriefcaseBusiness} label="Active work value" value={financial ? money(financial.summary.activeWorkValue, currency) : "Unavailable"} detail="current assignments" />
        <MobileMetric icon={Users} label="Connections" value={activeConnections.length} detail={incoming.length ? `${incoming.length} waiting` : "freelancer relationships"} />
      </section>
      <section className="overflow-hidden rounded-xl border border-border bg-muted/30"><div className="flex flex-wrap items-start justify-between gap-2 border-b border-border bg-card/60 px-3.5 py-3"><div className="flex items-start gap-2"><span className="mt-0.5 flex size-7 shrink-0 items-center justify-center rounded-lg bg-accent text-primary"><ClipboardList className="size-3.5" /></span><div><p className="text-body font-semibold text-foreground">Work summary</p><p className="mt-0.5 text-metadata text-muted-foreground">Assignment activity at a glance.</p></div></div></div><div className="grid grid-cols-2 divide-x divide-y divide-border"><MobileSummary label="Assignments" value={financial?.summary.totalAssignments ?? "Unavailable"} /><MobileSummary label="Active" value={financial?.summary.activeAssignments ?? "Unavailable"} accent /><MobileSummary label="Completed" value={financial?.summary.completedAssignments ?? "Unavailable"} /><MobileSummary label="Avg. verified value" value={financial ? money(financial.summary.averageCompletedAssignmentValue, currency) : "Unavailable"} accent /></div></section>
      <section className="min-w-0 overflow-hidden rounded-xl border border-primary/25 bg-card shadow-[var(--shadow-subtle)]"><div className="flex flex-wrap items-start justify-between gap-2 border-b border-primary/15 px-3.5 py-3"><div className="flex items-start gap-2"><span className="mt-0.5 flex size-7 shrink-0 items-center justify-center rounded-lg bg-primary text-primary-foreground"><WalletCards className="size-3.5" /></span><div><p className="text-body font-semibold text-foreground">Spending history</p><p className="mt-0.5 text-metadata text-muted-foreground">Recent work and payment activity.</p></div></div><Button render={<Link href="/dashboard/client/payments" />} nativeButton={false} variant="outline" size="sm" className="border-border bg-card text-foreground hover:bg-muted hover:text-foreground dark:bg-card dark:hover:bg-muted"><span>Open</span><ArrowRight data-icon="inline-end" /></Button></div>{financial?.history.length ? <ul className="divide-y divide-border px-3.5">{financial.history.slice(0, 4).map((item) => <li key={item.id} className="flex min-h-[4.5rem] items-center gap-3 py-3"><span className="min-w-0 flex-1"><span className="block truncate text-body font-semibold text-foreground">{item.title}</span><span className="mt-0.5 block truncate text-metadata text-muted-foreground">Freelancer: {item.counterpartyName}</span><span className="mt-1 block truncate text-metadata capitalize text-muted-foreground">{item.assignmentStatus.replaceAll("_", " ")} <span className="px-1 text-primary">·</span> {formatDate(item.updatedAt)}</span></span><span className="shrink-0 self-start pt-0.5 text-right"><span className="block text-body font-semibold text-foreground">{money(item.amount, item.currency)}</span><span className="mt-1 block text-metadata font-medium text-primary">{item.payment ? item.payment.status.replaceAll("_", " ") : "No claim"}</span></span></li>)}</ul> : <Empty icon={WalletCards} text="No spending history yet." href="/dashboard/client/payments" action="Open payments" />}</section>
      <section className="flex min-w-0 flex-col gap-3">
        <Card className="min-w-0"><CardContent className="p-0"><div className="flex flex-wrap items-start justify-between gap-2 border-b border-border px-3.5 py-3"><div><p className="text-body font-semibold text-foreground">Recent conversations</p><p className="mt-0.5 text-metadata text-muted-foreground">Messages from accepted connections.</p></div><Button render={<Link href="/dashboard/client/messages" />} nativeButton={false} variant="outline" size="sm" className="border-border bg-card text-foreground hover:bg-muted hover:text-foreground dark:bg-card dark:hover:bg-muted"><MessageSquare data-icon="inline-start" />Open messages</Button></div>{conversations.length ? <ul className="divide-y divide-border px-3.5">{conversations.slice(0, 4).map((conversation) => { const other = conversation.connection.requester.id === user.id ? conversation.connection.receiver : conversation.connection.requester; return <li key={conversation.id}><Link href={`/dashboard/client/messages/${conversation.id}`} className="flex min-h-14 items-center gap-3 py-2.5"><Avatar className="size-8"><AvatarFallback>{initials(other.name)}</AvatarFallback></Avatar><span className="min-w-0 flex-1"><span className="block truncate text-body font-semibold text-foreground">{other.name}</span><span className="block truncate text-metadata text-muted-foreground">{conversation.messages[0]?.body ?? "No messages yet"}</span></span><ArrowRight className="size-4 shrink-0 text-muted-foreground" /></Link></li>; })}</ul> : <Empty icon={MessageSquare} text="No conversations yet." href="/freelancers" action="Find freelancers" />}</CardContent></Card>
        <Card className="min-w-0 overflow-hidden shadow-none"><CardContent className="p-0"><div className="flex items-start gap-2 border-b border-border px-3.5 py-3"><span className="mt-0.5 flex size-7 shrink-0 items-center justify-center rounded-lg bg-muted text-primary"><ClipboardList className="size-3.5" /></span><div><p className="text-body font-semibold text-foreground">Current work</p><p className="mt-0.5 text-metadata text-muted-foreground">Assignments from your active conversations.</p></div></div>{activeWork.length ? <ul className="divide-y divide-border px-3.5">{activeWork.slice(0, 4).map((assignment) => <li key={assignment.id} className="flex min-h-13 items-center gap-3 py-2.5"><span className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-accent text-primary"><ClipboardList className="size-4" /></span><span className="min-w-0"><span className="block truncate text-body font-semibold text-foreground">{assignment.title}</span><span className="block text-metadata capitalize text-muted-foreground">{assignment.status.replaceAll("_", " ")}</span></span></li>)}</ul> : <Empty icon={ClipboardList} text="No active work yet." href="/dashboard/client/messages" action="Open messages" />}</CardContent></Card>
        <Card><CardContent className="p-3.5"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="text-body font-semibold text-foreground">Profile strength</p><p className="mt-0.5 text-metadata text-muted-foreground">Keep company information current.</p></div><span className="shrink-0 text-section-title font-semibold text-primary">{user.profileCompleteness}%</span></div><Progress value={user.profileCompleteness} className="mt-3 h-1.5 bg-muted" />{user.profileCompleteness < 100 && <Button render={<Link href="/onboarding" />} nativeButton={false} variant="ghost" size="sm" className="mt-2 px-0 text-primary hover:bg-muted hover:text-foreground"><span>Continue setup</span><ArrowRight data-icon="inline-end" /></Button>}</CardContent></Card>
        <Card><CardContent className="p-0"><div className="border-b border-border px-3.5 py-3"><p className="text-body font-semibold text-foreground">Workspace</p><p className="mt-0.5 text-metadata text-muted-foreground">Quick access to the tools you use most.</p></div><div className="grid grid-cols-2 gap-px bg-border">{ACTIONS.map(([title, description, href, Icon]) => <div key={href} className="min-w-0 bg-card p-3"><span className="flex size-7 items-center justify-center rounded-lg bg-accent text-accent-foreground"><Icon className="size-3.5" /></span><p className="mt-2 truncate text-body font-semibold text-foreground">{title}</p><p className="mt-0.5 truncate text-metadata text-muted-foreground">{description}</p><Button render={<Link href={href} />} nativeButton={false} variant="outline" size="sm" className="mt-2 border-border bg-card text-foreground hover:bg-muted hover:text-foreground dark:bg-card dark:hover:bg-muted"><span>Open</span><ArrowRight data-icon="inline-end" /></Button></div>)}</div></CardContent></Card>
      </section>
    </div>
    <div className="hidden min-w-0 md:block">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-metadata font-semibold uppercase tracking-[.14em] text-primary">Client workspace</p><h1 className="mt-1 font-heading text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">Welcome back, {user.name}</h1><p className="mt-1 text-muted-body text-muted-foreground">Your company, freelancer relationships, work, and payments at a glance.</p></div><Button render={<Link href="/dashboard/client/settings" />} nativeButton={false} variant="outline">Profile settings</Button></header>
    <section className="grid min-w-0 gap-3 lg:grid-cols-12">
      <Card className="lg:col-span-5"><CardContent className="flex min-h-42 flex-col justify-between gap-5 p-5"><div><p className="text-metadata font-medium text-muted-foreground">Verified payments</p><p className="mt-2 font-heading text-3xl font-semibold tracking-tight text-foreground">{financial ? money(financial.summary.verifiedAmount, currency) : "Unavailable"}</p><p className="mt-1 text-metadata text-muted-foreground">{financial ? `${financial.summary.pendingAmount > 0 ? money(financial.summary.pendingAmount, currency) : "No"} pending payment` : "Payment data could not be loaded"}</p></div><Link href="/dashboard/client/payments" className="inline-flex items-center text-body font-semibold text-primary hover:text-foreground">Open payments <ArrowRight className="ml-1 size-4" /></Link></CardContent></Card>
      <Metric icon={ClipboardList} label="Active work" value={activeWork.length} detail={activeWork.length === 1 ? "active assignment" : "active assignments"} />
      <Metric icon={BriefcaseBusiness} label="Work value" value={financial ? money(financial.summary.activeWorkValue, currency) : "Unavailable"} detail="current assignments" />
      <Metric icon={Users} label="Connections" value={activeConnections.length} detail={incoming.length ? `${incoming.length} request${incoming.length === 1 ? "" : "s"} waiting` : "freelancer relationships"} />
    </section>
    <section className="grid min-w-0 gap-3 lg:grid-cols-12">
      <Card className="min-w-0 lg:col-span-7"><CardHeader className="flex-row items-start justify-between gap-3"><div><CardTitle>Recent conversations</CardTitle><p className="mt-1 text-metadata text-muted-foreground">Messages from accepted connections.</p></div><Link href="/dashboard/client/messages" className="text-label font-semibold text-primary hover:text-foreground">Open messages</Link></CardHeader><CardContent>{conversations.length ? <ul className="divide-y divide-border">{conversations.slice(0, 4).map((conversation) => { const other = conversation.connection.requester.id === user.id ? conversation.connection.receiver : conversation.connection.requester; return <li key={conversation.id}><Link href={`/dashboard/client/messages/${conversation.id}`} className="flex min-h-14 items-center gap-3 py-3"><Avatar className="size-8"><AvatarFallback>{initials(other.name)}</AvatarFallback></Avatar><span className="min-w-0 flex-1"><span className="block truncate text-body font-semibold text-foreground">{other.name}</span><span className="block truncate text-metadata text-muted-foreground">{conversation.messages[0]?.body ?? "No messages yet"}</span></span><ArrowRight className="size-4 text-muted-foreground" /></Link></li>; })}</ul> : <Empty icon={MessageSquare} text="No conversations yet." href="/freelancers" action="Find freelancers" />}</CardContent></Card>
      <Card className="min-w-0 lg:col-span-5"><CardHeader><CardTitle>Current work</CardTitle><p className="mt-1 text-metadata text-muted-foreground">Assignments from your active conversations.</p></CardHeader><CardContent>{activeWork.length ? <ul className="divide-y divide-border">{activeWork.slice(0, 4).map((assignment) => <li key={assignment.id} className="flex min-h-14 items-center gap-3 py-3"><span className="flex size-8 items-center justify-center rounded-lg bg-accent text-accent-foreground"><ClipboardList className="size-4" /></span><span className="min-w-0"><span className="block truncate text-body font-semibold text-foreground">{assignment.title}</span><span className="block text-metadata capitalize text-muted-foreground">{assignment.status.replaceAll("_", " ")}</span></span></li>)}</ul> : <Empty icon={ClipboardList} text="No active work yet." href="/dashboard/client/messages" action="Open messages" />}</CardContent></Card>
      <Card className="lg:col-span-4"><CardContent className="p-5"><div className="flex items-center justify-between"><p className="text-body font-semibold">Profile strength</p><span className="text-section-title font-semibold text-primary">{user.profileCompleteness}%</span></div><Progress value={user.profileCompleteness} className="mt-4 h-1.5 bg-muted" />{user.profileCompleteness < 100 && <Link href="/onboarding" className="mt-3 inline-flex text-metadata font-semibold text-primary">Continue setup <ArrowRight className="ml-1 size-3" /></Link>}</CardContent></Card>
      <Card className="lg:col-span-8"><CardContent className="grid p-0 sm:grid-cols-2 lg:grid-cols-4">{ACTIONS.map(([title, description, href, Icon]) => <Link key={href} href={href} className="group flex min-h-34 flex-col justify-between gap-4 border-b border-border p-4 last:border-b-0 sm:border-r sm:last:border-r-0 lg:border-b-0"><span className="flex size-8 items-center justify-center rounded-lg bg-accent text-accent-foreground group-hover:bg-primary group-hover:text-primary-foreground"><Icon className="size-4" /></span><span><span className="block text-body font-semibold text-foreground">{title}</span><span className="mt-1 block text-metadata text-muted-foreground">{description}</span></span></Link>)}</CardContent></Card>
    </section>
    </div>
  </main>;
}
function Metric({ icon: Icon, label, value, detail }: { icon: typeof ClipboardList; label: string; value: string | number; detail: string }) { return <Card><CardContent className="p-5"><Icon className="size-4 text-primary" /><p className="mt-4 text-metadata text-muted-foreground">{label}</p><p className="mt-1 text-section-title font-semibold text-foreground">{value}</p><p className="mt-1 text-metadata text-muted-foreground">{detail}</p></CardContent></Card>; }
function MobileMetric({ icon: Icon, label, value, detail, accent = false }: { icon: typeof ClipboardList; label: string; value: string | number; detail: string; accent?: boolean }) { return <div className={`min-w-0 p-3 ${accent ? "bg-accent/20" : "bg-card"}`}><div className="flex items-start justify-between gap-2"><p className="truncate text-metadata font-medium text-muted-foreground">{label}</p><span className={`flex size-6 shrink-0 items-center justify-center rounded-md ${accent ? "bg-primary text-primary-foreground" : "bg-muted text-primary"}`}><Icon className="size-3.5" /></span></div><p className={`mt-2 truncate font-heading text-lg font-semibold tracking-tight ${accent ? "text-primary" : "text-foreground"}`}>{value}</p><p className="mt-0.5 truncate text-metadata text-muted-foreground">{detail}</p></div>; }
function MobileSummary({ label, value, accent = false }: { label: string; value: string | number; accent?: boolean }) { return <div className="min-w-0 p-3"><p className="truncate text-metadata text-muted-foreground">{label}</p><p className={`mt-1 truncate text-body font-semibold ${accent ? "text-primary" : "text-foreground"}`}>{value}</p></div>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", timeZone: "UTC" }).format(new Date(value)); }
function Empty({ icon: Icon, text, href, action }: { icon: typeof ClipboardList; text: string; href: string; action: string }) { return <div className="flex min-h-24 items-center gap-3"><span className="flex size-8 items-center justify-center rounded-lg bg-muted text-muted-foreground"><Icon className="size-4" /></span><div><p className="text-body text-muted-foreground">{text}</p><Link href={href} className="text-metadata font-semibold text-primary">{action}</Link></div></div>; }
