"use client";
import * as React from "react";
import { io } from "socket.io-client";
import { ClipboardList, LoaderCircle, RefreshCw, WalletCards } from "lucide-react";
import { getFinancialHistoryAction, type FinancialHistory } from "@/app/work-assignments/actions";
import { AppPageHeader } from "@/components/dashboard/app-page-header";
import { DashboardSection } from "@/components/dashboard/dashboard-section";
import { MetricCard } from "@/components/dashboard/metric-card";
import { StatePanel } from "@/components/dashboard/state-panel";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { getPublicBackendUrl } from "@/lib/public-backend-url";

type Props = { initialData: FinancialHistory; accessToken: string; refreshButtonClassName?: string; clientPresentation?: boolean };
const money = (value: number, currency: string) => new Intl.NumberFormat("en-IN", { style: "currency", currency, maximumFractionDigits: 2 }).format(value);
const label = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const paymentVariant = (status: string | undefined) => status?.includes("verified") ? "secondary" as const : "outline" as const;

export function FinancialHistory({ initialData, accessToken, refreshButtonClassName, clientPresentation = false }: Props) {
  const [data, setData] = React.useState(initialData); const [loading, setLoading] = React.useState(false); const [error, setError] = React.useState<string | null>(null);
  const refresh = React.useCallback(async () => { setLoading(true); setError(null); try { setData(await getFinancialHistoryAction()); } catch { setError("We couldn't refresh your payment history."); } finally { setLoading(false); } }, []);
  React.useEffect(() => { const socket = io(getPublicBackendUrl(), { auth: { token: accessToken }, transports: ["websocket", "polling"] }); const onAssignmentUpdated = () => void refresh(); socket.on("work-assignment.updated", onAssignmentUpdated); return () => { socket.off("work-assignment.updated", onAssignmentUpdated); socket.disconnect(); }; }, [accessToken, refresh]);
  const currency = data.history[0]?.currency ?? "INR"; const freelancer = data.role === "freelancer"; const counterpart = freelancer ? "Client" : "Freelancer";
  if (clientPresentation) return <ClientFinancialHistory data={data} loading={loading} error={error} refresh={refresh} />;
  return <div className="flex min-w-0 flex-col gap-section-gap">
    <AppPageHeader title={freelancer ? "Earnings" : "Payments"} description={freelancer ? "Verified income, pending payouts, and current work value." : "Verified spending, pending payments, and current work value."} action={<Button variant="outline" className={refreshButtonClassName} onClick={() => void refresh()} disabled={loading}>{loading ? <LoaderCircle className="animate-spin" /> : <RefreshCw />} Refresh</Button>} />
    <section className="grid min-w-0 gap-3 sm:grid-cols-3 sm:gap-4"><MetricCard icon={WalletCards} label={freelancer ? "Verified earnings" : "Verified payments"} value={money(data.summary.verifiedAmount, currency)} /><MetricCard icon={WalletCards} label="Pending payment" value={money(data.summary.pendingAmount, currency)} /><MetricCard icon={ClipboardList} label="Active work value" value={money(data.summary.activeWorkValue, currency)} /></section>
    <DashboardSection title="Work summary" description="A summary of your own assignments and verified value."><Card className="bg-muted/70 shadow-none"><CardContent className="grid grid-cols-2 gap-4 sm:grid-cols-4"><Summary label="Assignments" value={data.summary.totalAssignments} /><Summary label="Active" value={data.summary.activeAssignments} /><Summary label="Completed" value={data.summary.completedAssignments} /><Summary label="Average verified value" value={money(data.summary.averageCompletedAssignmentValue, currency)} /></CardContent></Card></DashboardSection>
    <DashboardSection title={freelancer ? "Payment history" : "Spending history"} description={`Amounts reflect your own work assignments with each ${counterpart.toLowerCase()}.`}>
      {error ? <StatePanel icon={WalletCards} title="Payment history unavailable" description={error} action={<Button onClick={() => void refresh()}>Retry</Button>} /> : data.history.length === 0 ? <StatePanel icon={WalletCards} title="No payment history yet" description="Work assignments and payment records will appear here as they are created." /> : <Card><CardContent className="divide-y divide-border">{data.history.map((item) => <article key={item.id} className="grid gap-3 py-4 first:pt-0 last:pb-0 sm:grid-cols-[minmax(0,1fr)_auto_auto] sm:items-center"><div className="min-w-0"><h3 className="truncate text-body font-semibold text-foreground">{item.title}</h3><p className="mt-1 text-muted-body text-muted-foreground">{counterpart}: {item.counterpartyName}</p><p className="mt-1 text-metadata text-muted-foreground">{item.deliverableSubmittedAt ? `Deliverable submitted ${new Date(item.deliverableSubmittedAt).toLocaleDateString("en-IN")}` : `Created ${new Date(item.createdAt).toLocaleDateString("en-IN")}`}</p></div><div className="text-body sm:text-right"><p className="font-semibold text-foreground">{money(item.amount, item.currency)}</p><p className="mt-1 text-metadata text-muted-foreground">{label(item.assignmentStatus)}</p></div><div className="flex flex-wrap items-center gap-2 sm:flex-col sm:items-end"><Badge variant={paymentVariant(item.payment?.status)}>{item.payment ? label(item.payment.status) : "No payment claim"}</Badge>{item.payment?.verifiedAt && <p className="text-metadata text-muted-foreground">Verified {new Date(item.payment.verifiedAt).toLocaleDateString("en-IN")}</p>}</div></article>)}</CardContent></Card>}
    </DashboardSection>
  </div>;
}
function ClientFinancialHistory({ data, loading, error, refresh }: { data: FinancialHistory; loading: boolean; error: string | null; refresh: () => Promise<void> }) {
  const currency = data.history[0]?.currency ?? "INR";
  return <div className="mx-auto flex w-full max-w-5xl min-w-0 flex-col gap-4 py-1 pb-24 text-[#F5F7FA] md:gap-5 md:pb-1">
    <header className="flex flex-wrap items-end justify-between gap-3 border-b border-[#27303A] pb-4"><div><p className="text-metadata font-semibold uppercase tracking-[.16em] text-[#36BDF6]">Client workspace</p><h1 className="mt-1 font-heading text-2xl font-semibold tracking-tight text-[#F5F7FA] sm:text-3xl">Payments</h1><p className="mt-1 text-metadata leading-5 text-[#A7B0BC]">Verified spending, pending payments, and current work value.</p></div><Button variant="outline" size="sm" className="border-[#27303A] bg-[#15181D] text-[#F5F7FA] hover:border-[#36BDF6]/60 hover:bg-[#191D23] hover:text-[#F5F7FA]" onClick={() => void refresh()} disabled={loading}>{loading ? <LoaderCircle className="animate-spin" /> : <RefreshCw className="text-[#36BDF6]" />} Refresh</Button></header>
    <section className="rounded-xl border border-[#36BDF6]/50 bg-[linear-gradient(135deg,#0D3448_0%,#15181D_72%)] p-4"><ClientMetric icon={WalletCards} label="Verified payments" value={money(data.summary.verifiedAmount, currency)} primary /></section>
    <section className="grid grid-cols-2 gap-3"><ClientMetric icon={WalletCards} label="Pending payment" value={money(data.summary.pendingAmount, currency)} pending /><ClientMetric icon={ClipboardList} label="Active work value" value={money(data.summary.activeWorkValue, currency)} /></section>
    <section className="overflow-hidden rounded-xl border border-[#27303A] bg-[linear-gradient(145deg,#191D23_0%,#15181D_65%)]"><div className="border-b border-[#27303A] px-3.5 py-3"><p className="text-body font-semibold text-[#F5F7FA]">Work summary</p><p className="mt-0.5 text-metadata text-[#A7B0BC]">A quick view of your assignments and verified value.</p></div><div className="grid grid-cols-2 divide-x divide-y divide-[#27303A]"><ClientSummary label="Assignments" value={data.summary.totalAssignments} /><ClientSummary label="Active" value={data.summary.activeAssignments} accent /><ClientSummary label="Completed" value={data.summary.completedAssignments} /><ClientSummary label="Avg. verified value" value={money(data.summary.averageCompletedAssignmentValue, currency)} accent /></div></section>
    <section className="min-w-0 overflow-hidden rounded-xl border border-primary/25 bg-card shadow-[var(--shadow-subtle)]"><div className="border-b border-primary/15 px-3.5 py-3"><p className="text-body font-semibold text-foreground">Spending history</p><p className="mt-0.5 text-metadata text-muted-foreground">Amounts reflect your own work assignments with each freelancer.</p></div>{error ? <div className="p-3.5"><StatePanel icon={WalletCards} title="Payment history unavailable" description={error} action={<Button size="sm" onClick={() => void refresh()}>Retry</Button>} /></div> : data.history.length === 0 ? <div className="flex min-h-28 items-center gap-3 p-3.5"><span className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-accent text-primary"><WalletCards className="size-4" /></span><div><p className="text-body font-semibold text-foreground">No payment history yet</p><p className="mt-0.5 text-metadata text-muted-foreground">Work assignments and payment records will appear here as they are created.</p></div></div> : <ul className="divide-y divide-border px-3.5">{data.history.map((item) => <li key={item.id} className="flex min-h-[4.75rem] items-center gap-3 py-3"><div className="min-w-0 flex-1"><h2 className="truncate text-body font-semibold text-foreground">{item.title}</h2><p className="mt-0.5 truncate text-metadata text-muted-foreground">Freelancer: {item.counterpartyName}</p><p className="mt-1 truncate text-metadata text-muted-foreground"><span className="capitalize">{item.assignmentStatus.replaceAll("_", " ")}</span> <span className="px-1 text-primary">·</span> {formatCompactDate(item.deliverableSubmittedAt ?? item.createdAt)}</p></div><div className="shrink-0 self-start pt-0.5 text-right"><p className="text-body font-semibold text-foreground">{money(item.amount, item.currency)}</p><p className="mt-1 text-metadata font-medium text-primary">{item.payment ? label(item.payment.status) : "No payment claim"}</p></div></li>)}</ul>}</section>
  </div>;
}
function ClientMetric({ icon: Icon, label, value, primary = false, pending = false }: { icon: typeof ClipboardList; label: string; value: string; primary?: boolean; pending?: boolean }) { return <div className={`min-w-0 ${primary ? "p-0" : `rounded-xl border border-[#27303A] p-3 ${pending ? "bg-[linear-gradient(135deg,#3A2D15_0%,#15181D_68%)]" : "bg-[linear-gradient(135deg,#0D3448_0%,#15181D_68%)]"}`}`}><div className="flex items-start justify-between gap-2"><p className="text-metadata font-medium text-[#A7B0BC]">{label}</p><span className={`flex size-7 shrink-0 items-center justify-center rounded-lg ${pending ? "bg-[#3A2D15] text-[#D7A84A]" : "bg-[#0D3448] text-[#36BDF6]"}`}><Icon className="size-3.5" /></span></div><p className={`mt-2 whitespace-nowrap font-heading font-semibold tracking-tight ${primary ? "text-3xl text-[#36BDF6]" : "text-lg text-[#F5F7FA]"}`}>{value}</p><p className="mt-1 text-metadata text-[#737D89]">{pending ? "Awaiting release" : primary ? "For completed work" : "In progress work"}</p></div>; }
function ClientSummary({ label, value, accent = false }: { label: string; value: string | number; accent?: boolean }) { return <div className="min-w-0 p-3"><p className="truncate text-metadata text-muted-foreground">{label}</p><p className={`mt-1 truncate text-body font-semibold ${accent ? "text-primary" : "text-foreground"}`}>{value}</p></div>; }
function formatCompactDate(value: string) { return new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(value)); }
function Summary({ label, value }: { label: string; value: string | number }) { return <div className="min-w-0"><p className="text-label text-muted-foreground">{label}</p><p className="mt-1 break-words text-body font-semibold text-foreground">{value}</p></div>; }
